version: 0.2

phases:
    install:
        commands:
            # Yarn installation
            - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            - sudo apt-get -y update
            - apt-get install -y yarn
            - yarn -v
            # Installing react dependencies
            - yarn install
    build:
        commands:
            # Building the react app and deploying to S3 bucket
            - yarn build
            - ls -al
            - aws s3 rm s3://badamtish.com --recursive
            - aws s3 sync build s3://badamtish.com/ --acl public-read
